### ISSUE TITLE
Will this be mantained?

### ISSUE THREAD

**Issue by fennectech** [sudofox/Backmemed#2]
Will this package be mantained  I can offer testing for changes

**Comment by sudofox** [comment]
yes, managing five projects at once rn, but certainly will be!

**Comment by fennectech** [comment]
Awesome  Im good at getting things to crash :D  (even when im NOT beta testing :/)

**Comment by sudofox** [comment]
@fennectech update: probably going to ditch Xdolf base itself and make backmemed a fork of Wurst -- I very much favor Wurst's menu system over anything else out there.

I use a self-maintained fork of wurst myself with a bunch of custom things added, but it doesn't really have a name -- I might rededicate the name to it instead.
